<?php
/**
 * Plugin Name: ✅ 04 UDEMY @wordpress/scripts
 * Description: A custom plugin with JS app built using @wordpress/scripts
 * Version: 1.0.0
 * Author: Craig West
 * Text Domain: my-@wp-plugin
 */

// Needs Node.js installed
// https://www.npmjs.com/package/@wordpress/scripts

if (!defined('ABSPATH')) {
    exit;
}

define('MY_PLUGIN_PATH', plugin_dir_path(__FILE__));
define('MY_PLUGIN_URL', plugin_dir_url(__FILE__));

/**
 * Add admin menu
 */
add_action('admin_menu', 'my_plugin_add_admin_menu');

function my_plugin_add_admin_menu() {
    add_menu_page(
        '@wordpress/scripts App',
        '04 @WP SCRIPTS',
        'manage_options',
        'my-custom-app',
        'my_plugin_render_admin_page',
        'dashicons-admin-generic',
        4.1
    );
}

/**
 * Render admin page
 */
function my_plugin_render_admin_page() {
    include MY_PLUGIN_PATH . 'includes/wp-admin-page.php';
}

/**
 * Enqueue scripts for admin page
 */
add_action('admin_enqueue_scripts', 'my_plugin_enqueue_scripts');

function my_plugin_enqueue_scripts($hook) {
    // Only load on our plugin page
    if ($hook !== 'toplevel_page_my-custom-app') {
        return;
    }

    // Safety check to ensure the build files exist but not essential for JS and CSS files to load.
    $asset_file_path = MY_PLUGIN_PATH . 'build/index.asset.php';
    
    if (!file_exists($asset_file_path)) {
        add_action('admin_notices', function() {
            echo '<div class="notice notice-error"><p>';
            echo 'My Custom Plugin: Build files not found. Please run <code>npm run build</code> in the plugin directory.';
            echo '</p></div>';
        });
        return;
    }

    $asset_file = include $asset_file_path;

    // These two files are generated by the build process and are required to load the React app. We can create these from other build workflows, but for this example, we are using @wordpress/scripts - see teh Langchain plugin.

    wp_enqueue_script(
        'my-custom-app',
        MY_PLUGIN_URL . 'build/index.js',
        $asset_file['dependencies'],
        $asset_file['version'],
        true
    );

    wp_enqueue_style(
        'my-custom-app-style',
        MY_PLUGIN_URL . 'build/style-index.css',
        [],
        $asset_file['version']
    );

    // Pass data to JavaScript
    wp_localize_script('my-custom-app', 'myPluginData', [
        'apiUrl' => rest_url('my-plugin/v1/'),
        'nonce' => wp_create_nonce('wp_rest'),
        'currentCount' => get_option('my_plugin_count', 0),
    ]);
}

/**
 * Register REST API routes
 */
add_action('rest_api_init', 'my_plugin_register_routes');

function my_plugin_register_routes() {
    register_rest_route('my-plugin/v1', '/save', [
        'methods' => 'POST',
        'callback' => 'my_plugin_save_data',
        'permission_callback' => function() {
            return current_user_can('manage_options');
        },
    ]);

    register_rest_route('my-plugin/v1', '/get', [
        'methods' => 'GET',
        'callback' => 'my_plugin_get_data',
        'permission_callback' => function() {
            return current_user_can('manage_options');
        },
    ]);
}

/**
 * Save data via REST API
 */
function my_plugin_save_data($request) {
    $data = $request->get_json_params();
    $count = isset($data['count']) ? intval($data['count']) : 0;
    
    update_option('my_plugin_count', $count);
    
    return new WP_REST_Response([
        'success' => true,
        'count' => $count,
        'message' => 'Data saved successfully',
    ], 200);
}

/**
 * Get data via REST API
 */
function my_plugin_get_data($request) {
    $count = get_option('my_plugin_count', 0);
    
    return new WP_REST_Response([
        'success' => true,
        'count' => intval($count),
    ], 200);
}

/**
 * Plugin activation hook
 */
register_activation_hook(__FILE__, 'my_plugin_activate');

function my_plugin_activate() {
    // Set default option
    add_option('my_plugin_count', 0);
}

/**
 * Plugin deactivation hook
 */
register_deactivation_hook(__FILE__, 'my_plugin_deactivate');

function my_plugin_deactivate() {
    // Cleanup if needed
}
