<?php
/**
 * Plugin Name: ✅ 30 UDEMY LANGGRAPH 
 * Description: A simple WordPress plugin demonstrating LangGraph.js integration with OpenAI
 * Version: 1.0.0
 * Author: Craig West
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Enqueue bundled JavaScript and CSS from the build folder
 * This is generated by @wordpress/scripts from src/index.js
 */
function wplg_enqueue_scripts($hook) {
    // Only enqueue on our plugin's admin page
    if ($hook !== 'toplevel_page_wp-langgraph-demo') {
        return;
    }

    // Enqueue the CSS file (built from src)
    wp_enqueue_style(
        'wp-langgraph',
        plugin_dir_url(__FILE__) . 'build/style-index.css',
        array(),
        '1.0.0'
    );

    // Enqueue the JavaScript file (built from src)
    wp_enqueue_script(
        'wp-langgraph',
        plugin_dir_url(__FILE__) . 'build/index.js',
        array(),
        '1.0.0',
        true
    );
}
add_action('admin_enqueue_scripts', 'wplg_enqueue_scripts');

/**
 * Add admin menu page
 * Menu position: 30 (as requested)
 */
function wplg_add_admin_menu() {
    add_menu_page(
        '30 UDEMY LangGraph Demo',  // Page title
        '30 LANGGRAPH',              // Menu title
        'manage_options',            // Capability
        'wp-langgraph-demo',         // Menu slug
        'wplg_render_admin_page',    // Callback function
        'dashicons-networking',      // Icon (network icon for graph)
        30                           // Position (as requested)
    );
}
add_action('admin_menu', 'wplg_add_admin_menu');

/**
 * Render the admin page
 * Includes the template from admin folder
 */
function wplg_render_admin_page() {
    include plugin_dir_path(__FILE__) . 'admin/admin-page-template.php';
}

/**
 * AJAX endpoint to get OpenAI API key from database
 * This avoids using dotenv - key is stored in WP options
 */
function wplg_get_api_key() {
    // Simple AJAX without nonce (as requested)
    
    // Get the API key from WordPress options
    // Using the same option name as 02-wp-basic-agent for consistency
    $api_key = get_option('wp_basic_agent_api_key', '');
    
    if (empty($api_key)) {
        wp_send_json_error(array(
            'message' => 'No API key found. Please save your OpenAI API key in the 02 AGENT JS settings page first.'
        ));
    } else {
        wp_send_json_success(array(
            'api_key' => $api_key
        ));
    }
}
add_action('wp_ajax_wplg_get_api_key', 'wplg_get_api_key');

/**
 * AJAX endpoint to save a test message (example of saving form data)
 * Uses AJAX without nonces as requested
 */
function wplg_save_test_data() {
    // Get the posted data
    $test_data = isset($_POST['test_data']) ? sanitize_text_field($_POST['test_data']) : '';
    
    if (empty($test_data)) {
        wp_send_json_error(array(
            'message' => 'No data provided'
        ));
    }
    
    // Save to options (just an example)
    update_option('wplg_last_test', $test_data);
    
    wp_send_json_success(array(
        'message' => 'Data saved successfully',
        'data' => $test_data
    ));
}
add_action('wp_ajax_wplg_save_test_data', 'wplg_save_test_data');
