<?php
/**
 * Plugin Name: ✅ 30 UDEMY LANGGRAPH 
 * Description: A simple WordPress plugin demonstrating LangGraph.js integration with OpenAI
 * Version: 1.0.0
 * Author: Craig West
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Enqueue bundled JavaScript and CSS from the build folder
 * This is generated by @wordpress/scripts from src/index.js
 */
function wplg_enqueue_scripts($hook) {
    // Only enqueue on our plugin's admin page
    if ($hook !== 'toplevel_page_wp-langgraph-demo') {
        return;
    }

    // Enqueue the CSS file (built from src)
    wp_enqueue_style(
        'wp-langgraph',
        plugin_dir_url(__FILE__) . 'build/style-index.css',
        array(),
        '1.0.0'
    );

    // Enqueue the JavaScript file (built from src)
    wp_enqueue_script(
        'wp-langgraph',
        plugin_dir_url(__FILE__) . 'build/index.js',
        array(),
        '1.0.0',
        true
    );
}
add_action('admin_enqueue_scripts', 'wplg_enqueue_scripts');

/**
 * Add admin menu page
 * Menu position: 4.95 (as requested)
 */
function wplg_add_admin_menu() {
    add_menu_page(
        '30 UDEMY LangGraph Demo',  // Page title
        '30 LANGGRAPH',              // Menu title
        'manage_options',            // Capability
        'wp-langgraph-demo',         // Menu slug
        'wplg_render_admin_page',    // Callback function
        'dashicons-networking',      // Icon (network icon for graph)
        4.95                         // Position (as requested)
    );
}
add_action('admin_menu', 'wplg_add_admin_menu');

/**
 * Render the admin page
 * Includes the template from admin folder
 */
function wplg_render_admin_page() {
    include plugin_dir_path(__FILE__) . 'admin/admin-page-template.php';
}

/**
 * AJAX endpoint to get OpenAI API key from database
 * This avoids using dotenv - key is stored in WP options
 */
function wplg_get_api_key() {
    // Simple AJAX without nonce (as requested)
    
    // Get the API key from WordPress options
    // Using the same option name as 02-wp-basic-agent for consistency
    $api_key = get_option('wp_basic_agent_api_key', '');
    
    if (empty($api_key)) {
        wp_send_json_error(array(
            'message' => 'No API key found. Please save your OpenAI API key in the 02 AGENT JS settings page first.'
        ));
    } else {
        wp_send_json_success(array(
            'api_key' => $api_key
        ));
    }
}
add_action('wp_ajax_wplg_get_api_key', 'wplg_get_api_key');

/**
 * AJAX endpoint to save a test message (example of saving form data)
 * Uses AJAX without nonces as requested
 */
function wplg_save_test_data() {
    // Get the posted data
    $test_data = isset($_POST['test_data']) ? sanitize_text_field($_POST['test_data']) : '';

    if (empty($test_data)) {
        wp_send_json_error(array(
            'message' => 'No data provided'
        ));
    }

    // Save to options (just an example)
    update_option('wplg_last_test', $test_data);

    wp_send_json_success(array(
        'message' => 'Data saved successfully',
        'data' => $test_data
    ));
}
add_action('wp_ajax_wplg_save_test_data', 'wplg_save_test_data');

/**
 * AJAX endpoint to get categories and tags statistics
 */
function wplg_get_categories_tags_stats() {
    // Get all categories
    $categories = get_categories(array(
        'hide_empty' => false,
    ));

    $category_stats = array();
    foreach ($categories as $category) {
        $category_stats[] = array(
            'name' => $category->name,
            'count' => $category->count,
            'id' => $category->term_id
        );
    }

    // Get all tags
    $tags = get_tags(array(
        'hide_empty' => false,
    ));

    $tag_stats = array();
    foreach ($tags as $tag) {
        $tag_stats[] = array(
            'name' => $tag->name,
            'count' => $tag->count,
            'id' => $tag->term_id
        );
    }

    wp_send_json_success(array(
        'categories' => $category_stats,
        'tags' => $tag_stats
    ));
}
add_action('wp_ajax_wplg_get_categories_tags_stats', 'wplg_get_categories_tags_stats');

/**
 * AJAX endpoint to get a random post and translate to French
 */
function wplg_get_random_post_french() {
    // Get API key for translation
    $api_key = get_option('wp_basic_agent_api_key', '');

    if (empty($api_key)) {
        wp_send_json_error(array(
            'message' => 'No API key found for translation'
        ));
        return;
    }

    // Get a random post
    $random_post = get_posts(array(
        'numberposts' => 1,
        'orderby' => 'rand',
        'post_status' => 'publish'
    ));

    if (empty($random_post)) {
        wp_send_json_error(array(
            'message' => 'No published posts found'
        ));
        return;
    }

    $post = $random_post[0];
    $post_content = $post->post_content;
    $post_title = $post->post_title;

    // Translate to French using OpenAI
    $translation_prompt = "Translate the following English text to French. Provide only the translation, no additional text:\n\nTitle: {$post_title}\n\nContent: {$post_content}";

    $response = wp_remote_post('https://api.openai.com/v1/chat/completions', array(
        'headers' => array(
            'Authorization' => 'Bearer ' . $api_key,
            'Content-Type' => 'application/json',
        ),
        'body' => json_encode(array(
            'model' => 'gpt-4o-mini',
            'messages' => array(
                array(
                    'role' => 'user',
                    'content' => $translation_prompt
                )
            ),
            'max_tokens' => 2000,
            'temperature' => 0.3
        )),
        'timeout' => 30
    ));

    if (is_wp_error($response)) {
        wp_send_json_error(array(
            'message' => 'Translation API request failed'
        ));
        return;
    }

    $body = wp_remote_retrieve_body($response);
    $data = json_decode($body, true);

    if (isset($data['error'])) {
        wp_send_json_error(array(
            'message' => 'Translation API error: ' . $data['error']['message']
        ));
        return;
    }

    $translated_text = $data['choices'][0]['message']['content'];

    wp_send_json_success(array(
        'original_title' => $post_title,
        'original_content' => $post_content,
        'translated_text' => $translated_text,
        'post_id' => $post->ID
    ));
}
add_action('wp_ajax_wplg_get_random_post_french', 'wplg_get_random_post_french');

/**
 * AJAX endpoint for deep research tool - get all posts for a category
 */
function wplg_deep_research_category() {
    $category_name = isset($_POST['category_name']) ? sanitize_text_field($_POST['category_name']) : '';

    if (empty($category_name)) {
        wp_send_json_error(array(
            'message' => 'No category name provided'
        ));
        return;
    }

    // Find the category by name (case-insensitive)
    $category = get_term_by('name', $category_name, 'category');

    // If not found by exact name, try slug
    if (!$category) {
        $category = get_term_by('slug', $category_name, 'category');
    }

    // If still not found, try partial name match
    if (!$category) {
        $categories = get_categories(array(
            'name__like' => $category_name,
            'hide_empty' => false,
        ));
        if (!empty($categories)) {
            $category = $categories[0];
        }
    }

    if (!$category) {
        wp_send_json_error(array(
            'message' => "Category '{$category_name}' not found"
        ));
        return;
    }

    // Get all posts in this category
    $posts = get_posts(array(
        'category' => $category->term_id,
        'numberposts' => -1, // Get all posts
        'post_status' => 'publish',
        'orderby' => 'date',
        'order' => 'DESC'
    ));

    $post_data = array();
    foreach ($posts as $post) {
        $post_data[] = array(
            'id' => $post->ID,
            'title' => $post->post_title,
            'content' => $post->post_content,
            'excerpt' => $post->post_excerpt ?: wp_trim_words($post->post_content, 30),
            'date' => $post->post_date,
            'url' => get_permalink($post->ID)
        );
    }

    wp_send_json_success(array(
        'category_name' => $category->name,
        'category_id' => $category->term_id,
        'posts' => $post_data,
        'total_posts' => count($post_data)
    ));
}
add_action('wp_ajax_wplg_deep_research_category', 'wplg_deep_research_category');
